# Generated by Django 5.2.9 on 2025-12-15 21:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JagdLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wildart', models.CharField(choices=[('Schalenwild', [('rehbock', 'Rehbock'), ('ricke', 'Ricke'), ('rehkitz', 'Rehkitz'), ('schwarzwild', 'Schwarzwild'), ('rotwild', 'Rotwild'), ('damwild', 'Damwild'), ('muffelwild', 'Muffelwild'), ('gamswild', 'Gamswild')]), ('Niederwild', [('hase', 'Hase'), ('wildkaninchen', 'Wildkaninchen'), ('fasan', 'Fasan'), ('rebhuhn', 'Rebhuhn'), ('wildente', 'Wildente'), ('wildgans', 'Wildgans'), ('wildtaube', 'Wildtaube')]), ('Raubwild', [('fuchs', 'Fuchs'), ('dachs', 'Dachs'), ('marder', 'Marder'), ('waschbaer', 'Waschbaer'), ('marderhund', 'Marderhund')]), ('Sonstiges', [('sonstiges', 'Sonstiges')])], max_length=50)),
                ('datum', models.DateField(default=datetime.date.today)),
                ('uhrzeit', models.TimeField(blank=True, null=True)),
                ('revier', models.CharField(blank=True, max_length=200)),
                ('geschlecht', models.CharField(choices=[('m', 'Maennlich'), ('w', 'Weiblich'), ('u', 'Unbekannt')], default='u', max_length=1)),
                ('gewicht', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('alter_geschaetzt', models.CharField(blank=True, max_length=50)),
                ('jagdart', models.CharField(blank=True, max_length=100)),
                ('waffe', models.CharField(blank=True, max_length=200)),
                ('entfernung', models.IntegerField(blank=True, null=True)),
                ('notizen', models.TextField(blank=True)),
                ('wetter', models.CharField(blank=True, max_length=100)),
                ('temperatur', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jagdeintrag',
                'verbose_name_plural': 'Jagdeintraege',
                'ordering': ['-datum', '-uhrzeit'],
            },
        ),
    ]
