# Generated by Django 6.0 on 2025-12-15 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jagdlog',
            options={'ordering': ['-datum', '-uhrzeit', '-created_at'], 'verbose_name': 'Jagdtagebuch-Eintrag', 'verbose_name_plural': 'Jagdtagebuch-Einträge'},
        ),
        migrations.AddField(
            model_name='jagdlog',
            name='wildart_custom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Eigene Wildart'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='alter_geschaetzt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Geschätztes Alter'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='datum',
            field=models.DateField(verbose_name='Erlegungsdatum'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='entfernung',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Schussentfernung (m)'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='geschlecht',
            field=models.CharField(choices=[('m', '♂ Männlich'), ('w', '♀ Weiblich'), ('u', '? Unbekannt')], default='u', max_length=1, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='gewicht',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Gewicht (kg)'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='jagdart',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jagdart'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='notizen',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='revier',
            field=models.CharField(blank=True, max_length=200, verbose_name='Revier/Ort'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='temperatur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatur (°C)'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='uhrzeit',
            field=models.TimeField(blank=True, null=True, verbose_name='Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jagd_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='waffe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Waffe/Kaliber'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='wetter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wetterbedingungen'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='wildart',
            field=models.CharField(max_length=50, verbose_name='Wildart'),
        ),
    ]
