# Generated by Django 6.0 on 2025-12-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagd', '0002_alter_jagdlog_options_jagdlog_wildart_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jagdlog',
            name='trophaee',
            field=models.BooleanField(default=False, verbose_name='Trophäe aufgehoben'),
        ),
    ]
