# Generated by Django 6.0 on 2025-12-16 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagd', '0003_jagdlog_trophaee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Reviername')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('groesse_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Größe (ha)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviere', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revier',
                'verbose_name_plural': 'Reviere',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Hochsitz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name/Bezeichnung')),
                ('typ', models.CharField(choices=[('kanzel', '🏠 Kanzel'), ('leiter', '🪜 Leitersitz'), ('druckjagdbock', '🎯 Drückjagdbock'), ('ansitzschirm', '🏕️ Ansitzschirm'), ('sonstiges', '📍 Sonstiges')], default='kanzel', max_length=50, verbose_name='Typ')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='GPS Breitengrad')),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='GPS Längengrad')),
                ('zustand', models.CharField(choices=[('gut', '✅ Gut'), ('reparatur', '🔧 Reparatur nötig'), ('schlecht', '⚠️ Schlecht'), ('neu', '🆕 Neu')], default='gut', max_length=20, verbose_name='Zustand')),
                ('baujahr', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baujahr')),
                ('letzte_kontrolle', models.DateField(blank=True, null=True, verbose_name='Letzte Kontrolle')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hochsitze', to=settings.AUTH_USER_MODEL)),
                ('revier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hochsitze', to='jagd.revier', verbose_name='Revier')),
            ],
            options={
                'verbose_name': 'Hochsitz',
                'verbose_name_plural': 'Hochsitze',
                'ordering': ['revier__name', 'name'],
            },
        ),
    ]
