# Generated by Django 6.0 on 2025-12-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagd', '0004_add_revier_hochsitz'),
    ]

    operations = [
        migrations.AddField(
            model_name='jagdlog',
            name='hochsitz_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jagd_eintraege', to='jagd.hochsitz', verbose_name='Hochsitz'),
        ),
        migrations.AddField(
            model_name='jagdlog',
            name='revier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jagd_eintraege', to='jagd.revier', verbose_name='Revier'),
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='revier',
            field=models.CharField(blank=True, max_length=200, verbose_name='Revier/Ort (alt)'),
        ),
    ]
