# Generated by Django 6.0 on 2025-12-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagd', '0005_jagdlog_hochsitz_ref_jagdlog_revier_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jagdlog',
            name='revier',
        ),
        migrations.AlterField(
            model_name='jagdlog',
            name='revier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jagd_eintraege', to='jagd.revier', verbose_name='Revier'),
        ),
    ]
