# Generated by Django 6.0 on 2025-12-16 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagd', '0006_remove_jagdlog_revier_alter_jagdlog_revier_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('typ', models.CharField(choices=[('buechse', '🎯 Büchse'), ('flinte', '🔫 Flinte'), ('drilling', '🔫 Drilling'), ('kombiniert', '🔫 Kombinierte Waffe'), ('kurzwaffe', '🔫 Kurzwaffe'), ('sonstiges', '📍 Sonstiges')], default='buechse', max_length=50, verbose_name='Waffentyp')),
                ('hersteller', models.CharField(blank=True, max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(blank=True, max_length=100, verbose_name='Modell')),
                ('kaliber', models.CharField(max_length=100, verbose_name='Kaliber')),
                ('seriennummer', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('kaufdatum', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('wbk_nummer', models.CharField(blank=True, max_length=50, verbose_name='WBK-Nummer')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waffen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waffe',
                'verbose_name_plural': 'Waffen',
                'ordering': ['name'],
            },
        ),
    ]
