# Generated by Django 6.0 on 2025-12-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagd', '0007_waffe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jagdlog',
            name='waffe',
        ),
        migrations.AddField(
            model_name='jagdlog',
            name='waffe_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jagd_eintraege', to='jagd.waffe', verbose_name='Waffe'),
        ),
    ]
